### ISSUE TITLE
legacy ssl and socks

### ISSUE THREAD

**Issue by vinnitu** [JoshGlazebrook/socks#10]
If I have tls.connect(port, host, ...) in my nodejs app, can I use socks to proxy such connection?

I planed to do it with ssh my_ssh_server_profile -D port

**Comment by JoshGlazebrook** [comment]
The closest thing would be to use the built in sockagent.

https://github.com/JoshGlazebrook/socks#using-socks-as-an-http-agent

Other than the agent, the socks library is just a bare bones tcp socket after the proxy handshake is done.
