### ISSUE TITLE
socks shouldn't bundle docs folder for end users

### ISSUE THREAD

**Issue by mcmxcdev** [JoshGlazebrook/socks#100]
According to a check with https://github.com/duniul/clean-modules, the whole `docs` folder is included into `node_modules` for end users.

https://github.com/JoshGlazebrook/socks/blob/master/.npmignore should be updated accordingly.

**Comment by JoshGlazebrook** [comment]
The docs folder just is examples?

**Comment by mcmxcdev** [comment]
Yes, but it means that every user has to download them as part of installation, no matter if they view them or not. 

It would be better to just link to them on your repo and keep them ignored from npm publishing.
