### ISSUE TITLE
Check for valid connection.

### ISSUE THREAD

**Issue by issy123** [JoshGlazebrook/socks#12]
I am using socks as an Http agent.

Is there some way I could check if the connection to the socks server is established and is working correctly?

**Comment by talmobi** [comment]
Why not make a request using the agent and see if it fails? Then you'll know either the agent is configured wrong or the proxy server is failing.

On a slightly related note - I made a tiny wrapper using [socks](https://github.com/JoshGlazebrook/socks) and [request](https://github.com/request/request) to proxy requests through the tor network - to make sure my SOCKS agents are correctly going through tor I make requests to https://www.ipify.org/ and make sure the ip's are from tor nodes.

**Comment by issy123** [comment]
Could you make an example code?

From there on I could edit it:)

Many thanks

**Comment by talmobi** [comment]
```
var Socks = require('socks');
var http = require('http');

var agent = new Socks.Agent({
  proxy: {
    ipaddress: "localhost",
    port: 80,
    type: 5
  }},
  false, // not https
  false // rejectUnauthorized
);

var opts = {
  hostname: "google.com",
  port: "80",
  agent: agent
};

var req = http.request(opts, function (res) {
  // no error with agent
  console.log("status: " + res.statusCode);
});

req.on('error', function (err) {
  // failed
  console.log(err);
});

req.end(); // finish and send the request
```

PS: this smells like an http://mywiki.wooledge.org/XyProblem

**Comment by issy123** [comment]
Ah great thanks!

No no this is not an x y problem haha

Didn't even know that there was an word for it.

But thanks I can work on this :)

**Comment by JoshGlazebrook** [comment]
Ah sorry I didn't see this in time!
