### ISSUE TITLE
TLS example ?

### ISSUE THREAD

**Issue by Stead68** [JoshGlazebrook/socks#13]
Hello,

I would like to use this library with a TLS socket. I didn't found how.
Can someone give me a quick example ?

Thank you :-)

**Comment by JoshGlazebrook** [comment]
https://github.com/JoshGlazebrook/socks#using-socks-as-an-http-agent

**Comment by Stead68** [comment]
Thanks for your reply, But I am not using it for HTTPS, it is for a raw TLS socket.

**Comment by gordalina** [comment]
This lib does not support it. But what you want is similar to what [socks-agent.js](https://github.com/JoshGlazebrook/socks/blob/master/lib/socks-agent.js) does. If you take that code and refactor in your project you can get it to work. You'll still need the socks client.
