### ISSUE TITLE
Reuse Socks options between connections

### ISSUE THREAD

**Issue by yciabaud** [JoshGlazebrook/socks#14]
Hello,

I am using this module in https://github.com/feross/webtorrent/pull/874 and I have an issue using multiple connections at the same time.

It looks like modifying the options properties conflicts with the other instances of the module. We have to clone it before passing it to the module.

Please have a look at https://github.com/feross/webtorrent/pull/874#issuecomment-242218428 for reference.

I believe the options should be cloned or not modified to avoid bugs. What do you think?

**Comment by JoshGlazebrook** [comment]
V2 is now published and available. This issue is definitely fixed.
