### ISSUE TITLE
Reuse socks agent for multiple requests

### ISSUE THREAD

**Issue by yciabaud** [JoshGlazebrook/socks#15]
May be a side effect of #14, I cannot reuse the same agent for multiple requests. Looks like the new destination is conflicting with the previous one...

Do you think we can make the agent compatible with multiple requests?

**Comment by JoshGlazebrook** [comment]
Pull requests are certainly welcome. The agent was put together by @gordalina perhaps he can fix it up real quick?

**Comment by JoshGlazebrook** [comment]
V2 is now published and available. This issue is definitely fixed.
