### ISSUE TITLE
Synchronously create connection?

### ISSUE THREAD

**Issue by Miserlou** [JoshGlazebrook/socks#17]
I'd love to be able to use Socks in place of `net.connect`, which operates like this:

``` javascript
                connection = net.connect(port, host);
                hand_off_connection(connection);
```

Instead, with Socks, I have to:

``` javascript
        Socks.createConnection(options, function(err, socket, info) {
            if (err)
                console.log(err);
            else {
                socket.resume();
                hand_off_connection(socket);
            }
        });
```

This makes it a lot, lot harder to debug complicated network code. For setting up the connections, I don't mind doing it synchronously. Is there any way to do that?

**Comment by buildjosh** [comment]
Yes that can be added quite easily. I'm planning on revamping the library to allow for proxy chaining in the future (version 2) also.

**Comment by JoshGlazebrook** [comment]
Yes that can be added quite easily. I'm planning on revamping the library to allow for proxy chaining in the future (version 2) also.

**Comment by Miserlou** [comment]
Great! 😄 Looking forward to it.

I've tried using various Promise libraries, but honestly I feel like a dog chasing its own tail.

**Comment by JoshGlazebrook** [comment]
So I'm thinking something like this this?

```javascript

function handler(err, socket, info) {
    handle the proxy being connected... 
}

var socket = Socks.createConnection(options, handler);

**Comment by Miserlou** [comment]
Yeah, that would work for me, I don't need it to be truly synchronous, I just need the returned socket to be in the same context.

What would go inside handler? I guess the question is when would I call socket.resume()? [PS - I only ever need to call that once, right?]. Does it need to return anything?

**Comment by JoshGlazebrook** [comment]
Right so, the handler itself is the function that is called when the socks library has established the proxy connection to the remote host. This could also be done as an event, like socket.on('established') or something along those lines. I probably should have built events into the library as well. 

As far as the resume function, the socks library itself pauses the flow of incoming data, and resume will make data start coming in again. This is just to stop the loss of data if say you didn't attach a .on('data') event handler for a significant amount of time. Aka, it only needs to be called once.

**Comment by Miserlou** [comment]
Ah, gotcha!

Events would be another big + 1, although less pressing, but basically hooray to anything to get compatibility with the normal Sockets as high as possible. Obviously that'd be pretty huge, as it could mean basically drop-in proxy support for almost all existing Node apps with minimal effort. It looks like some of them were already working though, my on close event at least appeared to be firing as expected? Or maybe my code is funky. (Full disclosure: my code is more than funky.)

Another useful thing would be the ability to get the remote host for the socket somehow? I couldn't see how to do that, I could only get the local proxy. I think. I tested about a dozen different proxy libraries yesterday 😄 .
