### ISSUE TITLE
2.0.0 Ideas

### ISSUE THREAD

**Issue by JoshGlazebrook** [JoshGlazebrook/socks#18]
So I've finished re-writing smart-buffer in TypeScript, so now I'm moving on to Socks. Here is what I'm looking at accomplishing in this refresh.

## Improvements
* TypeScript Re-write
* Support for Promises when creating proxy connection
* Support for EventHandler events when creating proxy connection
    * This may require extending Socket #17 
* ~~Support for legacy createConnection method (backwards compatibility)~~
* Support for chaining proxies (CONNECT mode only) #11 
* Fix all bugs #14 #15 
* Tests!

## Potential additions
* Server implementation - this would make this library a client and a server.

## Breaking changes
* Remove agent as socks-proxy-agent is way more popular anyways.

**Comment by JoshGlazebrook** [comment]
Since it's coming up on almost a year of this issue being created, and the fact that smart buffer v4 is out, I will be revisiting v2 later this month.

**Comment by JoshGlazebrook** [comment]
Also, explicitly pinging @tootallnate as socks-proxy-agent gets heavy use of this.

**Comment by gordalina** [comment]
Having tests would be good for the project overall

**Comment by JoshGlazebrook** [comment]
@gordalina Definitely was already on my mind but I'll add that to the list as well.

**Comment by JoshGlazebrook** [comment]
I'm readying v2 for release in the next few days.

**Comment by JoshGlazebrook** [comment]
V2 is now published and available.
