### ISSUE TITLE
BIND command sent without CONNECT command

### ISSUE THREAD

**Issue by OriTheMan** [JoshGlazebrook/socks#19]
Hi,
i have client (using you lib),socks server, application server.
i want to use bind, but i see that the lib send onlu BIND command without CONNECT first.
as i know, socks server should get CONNECT and then BIND.

i see in my socks server that i receive only BIND and only 1 port opened.
i think it should be
CONNECT command - primary connection
BIND command - sent over the connection that already opened and receiving another port for communication (like FTP, 1 for commands and 1 for transfer data)

**Comment by buildjosh** [comment]
So with BIND, the primary connection to the SOCKS proxy server you initiate a CONNECT command, and then BIND is used in a separate socket connection (secondary connections) to the same proxy server. So with this library you would need two .createConnection() calls. 

https://www.ietf.org/rfc/rfc1928.txt

> It is expected that the client side of an application protocol will
   use the BIND request only to establish secondary connections after a
   primary connection is established using CONNECT.  In is expected that
   a SOCKS server will use DST.ADDR and DST.PORT in evaluating the BIND
   request.

Once you establish a connection with the CONNECT command, the connection over that socket acts like its directly connected so sending a BIND command would just be forwarded on to the server you had the proxy connect to. This is why BIND uses a secondary connection to the proxy server.
