### ISSUE TITLE
Setting it up as an agent

### ISSUE THREAD

**Issue by c0debreaker** [JoshGlazebrook/socks#24]
I'm currently using http-proxy-middleware. I'd like to use `socks` as an agent. Basically what I wanted to do is have http-proxy-middleware receive the HTTP request from the browser then forward all HTTP request to `socks`. However, I can't find any example where `socks` was used as an agent. Any help would be greatly appreciated.

**Comment by JoshGlazebrook** [comment]
The agent was removed but this probably answers your question: https://github.com/JoshGlazebrook/socks/issues/23

**Comment by JoshGlazebrook** [comment]
Feel free to re-open if you need more!
