### ISSUE TITLE
SocksClient.createConnection usage questions

### ISSUE THREAD

**Issue by houkk** [JoshGlazebrook/socks#28]
commond: connect
create client method: SocksClient.createConnection(options)    // async await

Can I monitor `connect`， `close`, ..etc events like net.Socket ?
Can I call `client.end()` ...etc methods like net.Socket ?
And how ?

**Comment by JoshGlazebrook** [comment]
If you're using the createConnection() factory method, it's going to spit out a regular net.Socket once the SOCKS proxy handshake is completed. 

Here are some examples: https://github.com/JoshGlazebrook/socks/blob/master/docs/examples/typescript/connectExample.md
