### ISSUE TITLE
Uncleared timeout caused process to hang.

### ISSUE THREAD

**Issue by NStal** [JoshGlazebrook/socks#32]
https://github.com/JoshGlazebrook/socks/blob/master/src/client/socksclient.ts#L281

Even connection established within seconds, this timer will still be pending around until default timeout is met. We should save the timer and clear it at some point, maybe when connection established.

**Comment by NStal** [comment]
Seems we've already got a pull request?
https://github.com/JoshGlazebrook/socks/pull/30

**Comment by JoshGlazebrook** [comment]
The other PR is merged and 2.2.1 is published.
