### ISSUE TITLE
Socks 5 and tor

### ISSUE THREAD

**Issue by arj03** [JoshGlazebrook/socks#39]
Latest version of tor doesn't work with socks anymore. Adding a fake username / password works. The same does changing protocol to 4. Here are the relevant parts of the documentation from tor that describes the change.

```
PreferSOCKSNoAuth

Ordinarily, when an application offers both "username/password authentication" and "no authentication" to Tor via SOCKS5, Tor selects username/password authentication so that IsolateSOCKSAuth can work. This can confuse some applications, if they offer a username/password combination then get confused when asked for one. You can disable this behavior, so that Tor will select "No authentication" when IsolateSOCKSAuth is disabled, or when this option is set.
```

and

```
IsolateSOCKSAuth
Don't share circuits with streams for which different SOCKS authentication was provided. (For HTTPTunnelPort connections, this option looks at the Proxy-Authorization and X-Tor-Stream-Isolation headers. On by default; you can disable it with NoIsolateSOCKSAuth.)
```

**Comment by JoshGlazebrook** [comment]
Are you sure this is a recent change? I'm pretty sure those options have been in the config for a while.

**Comment by talmobi** [comment]
@JoshGlazebrook I think this is an issue with the new version of tor that was recently published ~1.5 weeks ago: https://trac.torproject.org/projects/tor/ticket/29050

I had same issue popping up on my library/module and defaulting to using version 4 seemed like the best options (while still giving users control whatever they want to use): https://github.com/talmobi/tor-request/issues/39

I'm using `socks-proxy-agent` module in tor-request which uses your (this) module underneath -- so the issues are related.

**Comment by JoshGlazebrook** [comment]
Hmm, let me look into this a bit. I think a solution may be to just not send the flag that says the client supports user/password auth as an option, unless a user + pw is actually provided.

**Comment by talmobi** [comment]
A bit spooky how the related issues on our modules are both number 39 btw.

*x-files theme plays* https://www.youtube.com/watch?v=hAAlDoAtV7Y

**Comment by JoshGlazebrook** [comment]
I'm not able to easily get tor working at the moment, can one of you go into 

node_modules/socks/build/clint/socksclient.js

and on line 451, just comment it out?

> buff.writeUInt8(constants_1.Socks5Auth.UserPass);

And then test if it works like it used to?

**Comment by talmobi** [comment]
Will do, be right back

**Comment by talmobi** [comment]
The tor log doesn't throw auth error but the module timeouts.

**Comment by talmobi** [comment]
used socks@2.2.1 btw

**Comment by JoshGlazebrook** [comment]
Ah shit, also change the line 449 from 2 to 1.

**Comment by JoshGlazebrook** [comment]
@arj03 @talmobi This should be fixed, and I've published 2.2.3 to npm.

**Comment by talmobi** [comment]
Very nice~ This also fixes `socks-proxy-agent` because it has `~2.2.0` as its `socks` dependency (it automatically installs 2.2.3 now just verified.

**Comment by JoshGlazebrook** [comment]
fyi ^ - @TooTallNate

**Comment by arj03** [comment]
Thank you very much for the swift response! Wrote this yesterday evening and this morning all is fixed ❤️

**Comment by JoshGlazebrook** [comment]
https://github.com/torproject/tor/pull/670/files
