### ISSUE TITLE
Socks v5h is not supported

### ISSUE THREAD

**Issue by Virius** [JoshGlazebrook/socks#40]
With proxy where using  socks5h cause error "Received invalid Socks5 initial handshake (invalid socks version)"

**Comment by JoshGlazebrook** [comment]
As far as I know, socks5h is just a CURL option to have the domain resolved by the proxy. If you supply a domain to socks when creating a connection it should be doing this automatically. 

Do you have example code to share?

**Comment by JoshGlazebrook** [comment]
Please re-open if you still need help.
