### ISSUE TITLE
Why are we not allowing proxy to be a domain?

### ISSUE THREAD

**Issue by benkaiser** [JoshGlazebrook/socks#41]
Regarding this line:
https://github.com/JoshGlazebrook/socks/blob/d7f91b7bf58c6f80755b356e7777db6b75adff52/src/common/helpers.ts#L135

I'm using this socks5 proxy (redacted) `socks5://user:password@proxy-nl.privateinternetaccess.com:1080` and it works perfectly fine using curl, but it seems to be specifically disabled in this library. What is the reasoning behind this? does it really make sense?

Note: I've removed the line locally and it seems to work just fine.

**Comment by JoshGlazebrook** [comment]
You know, that's a good question 🙃

The shitty thing is we can remove the isIp() check, but the property is still ipaddress. I guess I could rename it to 'host' so it makes more sense and leave ipaddress for backwards compatibility.

**Comment by JoshGlazebrook** [comment]
This is now possible in v2.3.1

**Comment by benkaiser** [comment]
You legend! Thanks Josh!
