### ISSUE TITLE
please allow socket.connect() options to be passed

### ISSUE THREAD

**Issue by qp3ef** [JoshGlazebrook/socks#42]
Net's [```socket.connect```](https://nodejs.org/api/net.html#net_socket_connect_options_connectlistener) allows a number of additional connection options such as ```localAddress```, ```localPort```, ```lookup```, etc.

These cannot currently be passed to ```socket.connect```.

Perhaps making the following change would allow that:
 socks/src/client/socksclient.ts:310
```
(this._socket as net.Socket).connect(this._options.proxy);
```

Though I am not sure if the ```family``` option (IPv 4 or 6) needs to be explicitly specified when using this calling signature, or if ```socket.connect``` will determine this automatically. Docs seem to suggest the default is always ```4```.

**Comment by JoshGlazebrook** [comment]
I'll look into this as a possibility. You should be able to currently work around this by passing a socket into .connect():

https://github.com/JoshGlazebrook/socks/blob/master/src/client/socksclient.ts#L274

You would essentially create a socket and connect to proxy on your own, and then pass the socket into .connect() where this library does the handshake for you.

**Comment by JoshGlazebrook** [comment]
This is now built in - https://github.com/JoshGlazebrook/socks/releases/tag/2.3.3
