### ISSUE TITLE
socks with a TLS socket

### ISSUE THREAD

**Issue by nickvorie** [JoshGlazebrook/socks#43]
How would I create a TLS socket using this library? I can't connect on port 443.

**Comment by JoshGlazebrook** [comment]
This is what you're looking for - https://github.com/TooTallNate/node-socks-proxy-agent

**Comment by nickvorie** [comment]
@JoshGlazebrook I'm looking to work with raw sockets, not a HTTP(s) library. Any suggestions?

**Comment by JoshGlazebrook** [comment]
That's beyond the scope of this module. You'd need to look at how the TLS protocol is implemented and do it yourself, or use a module that handles it for you.

**Comment by nickvorie** [comment]
I have figured it out myself. If anyone else is trying to figure it out: https://github.com/nickvorie/node-socks-tls/blob/master/index.js
