### ISSUE TITLE
Need to pass connectListener to createConnection

### ISSUE THREAD

**Issue by apmcodes** [JoshGlazebrook/socks#63]
Using socks for SMTP and seems `connect` event is missed (fired) before attaching connect listener to the returned socket from createConnection. On `connect` need to return socket to the caller for further smtp communications, but instead receiving only data event. Can we pass a connectListener callback to the createConnection like net.socket 
```
const info = await socksClient.createConnection(connectionOpts);
socket.once('connect', () => {
   // Need to return socket to the caller
})
socket.on('data', (data) => {
    logger.debug('DATA %s' , data.toString());
});

```

```
DATA '220 mx.google.com ESMTP 132si11603197pgd.199 - gsmtp\r\n' 
```

**Comment by JoshGlazebrook** [comment]
The socket is returned in the promise returned by createConnection.

See: https://github.com/JoshGlazebrook/socks/blob/master/docs/examples/typescript/connectExample.md#using-createconnection-with-asyncawait

```typescript
    const info = await SocksClient.createConnection(options);

    console.log(info.socket);
    // <Socket ...>  (this is a raw net.Socket that is established to the destination host through the given proxy servers)

    info.socket.write('GET /json HTTP/1.1\nHost: ip-api.com\n\n');
    info.socket.on('data', (data) => {
      console.log(data.toString()); // ip-api.com sees that the last proxy (104.131.124.203) is connected to it and not the origin client (you).
```

The promise is only resolved once the SOCKS handshake is completed and the socket is ready to use.

**Comment by apmcodes** [comment]
Got it. Thanks!
