### ISSUE TITLE
Passing port as string crashes connection with non-specific error

### ISSUE THREAD

**Issue by 13protons** [JoshGlazebrook/socks#71]
I was getting stuck while trying to follow the documentation for FixieSocks, which references this module: 

[https://devcenter.heroku.com/articles/fixie-socks#using-with-node-js](https://devcenter.heroku.com/articles/fixie-socks#using-with-node-js)

In their example, they parse the port number out of an environment variable using regex, and then pass that on to `socks`. 

Following the example code broke the socket with a stack trace that looks like this:

```
SocksClientError: Invalid SOCKS proxy details were provided.
    at Object.validateSocksClientOptions (/Users/13protons/github/herl-os/node_modules/socks/build/common/helpers.js:27:15)
    at /Users/13protons/github/herl-os/node_modules/socks/build/client/socksclient.js:43:27
    at new Promise (<anonymous>)
    at Function.createConnection (/Users/13protons/github/herl-os/node_modules/socks/build/client/socksclient.js:40:16)
    at Object.<anonymous> (/Users/13protons/github/herl-os/sockstest.js:93:13)
```

I noticed by process of elimination that reverting the extracted port number back to a numeric `1080` fixed my connection, as did casting the matched port to a number, like this: 

```
port: Number(fixieValues[3]),
```

I've fixed my own problem here, but it may be appropriate to either mention the invalid port type in the error message or just do that casting for the user. 

Cheers

**Comment by JoshGlazebrook** [comment]
I looked at that heroku documentation and its actually for a different npm module. This repo is `socks` while those docs are using `socksjs`. 

But I agree the error messaging here should have more details.

**Comment by 13protons** [comment]
And if that wasn't already confusing enough, the example for connecting to mysql uses socksjs, ssl uses socksv5, and http/s uses socks 

<img width="405" alt="Screen Shot 2021-04-21 at 7 28 29 PM" src="https://user-images.githubusercontent.com/1456258/115634643-09717c00-a2d8-11eb-8c18-83e597209a50.png">
<img width="421" alt="Screen Shot 2021-04-21 at 7 28 40 PM" src="https://user-images.githubusercontent.com/1456258/115634647-0bd3d600-a2d8-11eb-93f4-9dbb839b33a0.png">
<img width="314" alt="Screen Shot 2021-04-21 at 7 28 50 PM" src="https://user-images.githubusercontent.com/1456258/115634650-0e363000-a2d8-11eb-8db7-59d5170946c6.png">


Perhaps FixieSocks needs an issue filed on their docs 😅
