### ISSUE TITLE
Troubles with SocksV4, when hostname contains domain

### ISSUE THREAD

**Issue by Pterko** [JoshGlazebrook/socks#8]
Good afternoon. First of all, sorry for my bad English :) . I think that implementation of socksv4 have a mistake. Here is an example of my steps, what I made to think so:
1. Visit https://www.npmjs.com/package/socks and copy a first example.
2. Search the Internet for any working socksv4 proxy server. You can check it here - https://incloak.com/proxy-checker/. I found this: 94.199.177.195:1080. At the time of writing it worked.
3. As a result, I write this code (on base of first example) :
```js
var Socks = require('socks');
 
var options = {
    proxy: {
        ipaddress: "94.199.177.195", //random socksv4 proxy-server, what i found in the internet 
        port: 1080,
        type: 4 // type is REQUIRED. Valid types: [4, 5]  (note 4 also works for 4a) 
    },
    target: {
        host: "google.com", // can be an ip address or domain (4a and 5 only) google.com ip = 64.233.161.101
        port: 80
    },
    command: 'connect'  // This defaults to connect, so it's optional if you're not using BIND or Associate. 
};
 
Socks.createConnection(options, function(err, socket, info) {
    if (err)
        console.log(err);
    else {
        // Connection has been established, we can start sending data now: 
        socket.write("GET / HTTP/1.1\nHost: google.com\n\n");
        socket.on('data', function(data) {
            console.log(data.length);
            console.log(data);
        });
 
        // PLEASE NOTE: sockets need to be resumed before any data will come in or out as they are paused right before this callback is fired. 
        socket.resume();
 
        // 569 
        // <Buffer 48 54 54 50 2f 31 2e 31 20 33 30 31 20 4d 6f 76 65 64 20 50 65... 
    }
});
```

When i execute this code, i receive error:
```[Error: Rejected (91)]```
But if we replace ```google.com``` by its ip (for me it's ```64.233.161.101```),  the code executes normally:
```js
521
<Buffer 48 54 54 50 2f 31 2e 31 20 33 30 32 20 46 6f 75 6e 64 0d 0a 43 61 63 68 65 2d 43 6f 6e 74 72 6f 6c 3a 20 70 72 69 76 61 74 65 0d 0a 43 6f 6e 74 65 6e 74 ...>
```
I think, that mistake in this fragment of code (socks-client.js):
```js
        // 4/4a  (connect, bind) - Supports domains & ipaddress
        function negotiateSocks4(options, socket, callback) {
            buff.writeUInt8(0x04);
            buff.writeUInt8(options.proxy.command);
            buff.writeUInt16BE(options.target.port);
            // ipv4 or domain?
            
            if (net.isIPv4(options.target.host)) {
                buff.writeBuffer(ip.toBuffer(options.target.host));
                buff.writeStringNT(options.proxy.userid);
            } else {
                buff.writeUInt8(0x00);
                buff.writeUInt8(0x00);
                buff.writeUInt8(0x00);
                buff.writeUInt8(0x01);
                buff.writeStringNT(options.proxy.userid);
                buff.writeStringNT(options.target.host);
            }
```
First branch of ```if``` works normally, but the second part (that executes, then hostname contains domain) have mistake. So, please help me resolve this problem.

**Comment by JoshGlazebrook** [comment]
The implementation of the SOCKS 4/4A protocols are correct. The problem is that only SOCKS servers that support the 4A protocol allow hostname lookups.

None of the websites out there seem to differentiate between 4 and 4a because there is no easy way to figure out if a server supports it or not. If you want guaranteed support for hostname lookups over a proxy you would need to use a SOCKS 5 proxy server.

I put together a little example using the socks4 npm module which implements the SOCKS 4 and 4A protocols. Connecting directly to that server that is supporting 4A's hostname lookups shows the implementation is correct.

```javascript
var socks = require('socks');
var server = require('socks4');


server.createServer().listen(1080);


var options = {
    proxy: {
        ipaddress: '127.0.0.1',
        port: 1080,
        type: 4
    },

    target: {
        host: 'google.com',
        port: 80
    }
};

socks.createConnection(options, function(err, socket, info) {
    if (err)
        return console.log('Error:', err);
    else
        console.log('Connected');

    socket.on('data', function(data) {
        console.log(data);
    });

    socket.resume();

    //...

});
```

```
Connected
```

**Comment by Pterko** [comment]
Thank you very much! Now, I figured out how to make everything work well! At the same time I want to say thank you for creating this module. :)
