### ISSUE TITLE
socket closing

### ISSUE THREAD

**Issue by asluchevskiy** [JoshGlazebrook/socks#9]
Hi,

I am trying to implement http-to-socks proxy using your lib.
My code is here: https://github.com/asluchevskiy/http-to-socks-proxy/blob/master/lib/proxy-server.js#L42

For example, after request throw tor `netstat -n | grep 9050` will show:
`tcp        0      0 127.0.0.1:49672         127.0.0.1:9050          TIME_WAIT `

So, as I can see, socket was not closed.

I tryied to add the following code:
```js
proxyResponse.on('end', function () {
    response.end();
    proxyRequest.socket.destroy(); // or     proxyResponse.socket.destroy(); ?!
});
```

But the result still the same. Also, I have a part of the code for https support here https://github.com/asluchevskiy/http-to-socks-proxy/blob/master/lib/proxy-server.js#L76

I also tried to add destroying, but without any results. Could you help me?
Also, it works fine, but when I making many concurrent connections errors begin to appear, like Connection Timed Out (and netstat shows some thousands of sockets).

I am using my own solution (or not privoxy for example) in case I have a few thousands socks proxies and need only one enter point throw http.

P.S. sorry for some mistakes in English

**Comment by JoshGlazebrook** [comment]
Not sure. I'll have to look into it.

**Comment by asluchevskiy** [comment]
Sorry, I made few commits and line numbers in my message upper is wrong now.
May be TIME_WAIT state of the sockets depends from the OS settings. I am using last Ubuntu (15.04) without any tune.

**Comment by asluchevskiy** [comment]
Today I added a local dns resolution and it's also fix some problems with a performance. So I am not sure now that my problems is associated with sockets, or not remote socks'es, for example.
But if you will give some adviсes it will be great. Thanks.
