### ISSUE TITLE
UDP associate example doesn't work properly

### ISSUE THREAD

**Issue by n1ckyrush** [JoshGlazebrook/socks#90]
Hello there, thanks for such a nice library.
I was testing UDP ASSOCIATE feature and was checking this page - https://github.com/JoshGlazebrook/socks/blob/master/docs/examples/javascript/associateExample.md 
I realized that it doesn't work as described and spent many hours trying to find the cause.
Here are some issues that I was able to discover and fix.

Issue 1.
Nothing happens when you launch this code, you need to call `client.connect()` to start actual request.
Otherwise it's just gonna sit there forever doing nothing.

Issue 2.
Here is the code from the example to send a request to remote DNS server.
```
const packet = SocksClient.createUDPFrame({
	remoteHost: { host: '8.8.8.8', port: 53 },
	data: Buffer.from('hello') // A DNS lookup in the real world.
});
```

Even if your proxy is working, this code won't trigger any response because it's invalid, so you might end up thinking that something wrong with the proxy.
You need to form a proper request for DNS server in order to get something back.

Here is my code looking up baidu domain name:
```
const packet = SocksClient.createUDPFrame({
	remoteHost: { host: '8.8.8.8', port: 53 },
	data: Buffer.from('\x12\x34\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x05\x62\x61\x69\x64\x75\x03\x63\x6f\x6d\x00\x00\x01\x00\x01')
});
```

This code triggers event `udpSocket.on('message', ...)` and you will actually see the response.

P.S. To be able to form proper packets for DNS servers, you can also try a package `dns-packet`.

**Comment by JoshGlazebrook** [comment]
> // A DNS lookup in the real world.
This comment is meant to imply this is obviously not a real DNS request packet.
