### ISSUE TITLE
SocksClientError: Invalid SOCKS proxy details were provided.

### ISSUE THREAD

**Issue by ChandlerAx** [JoshGlazebrook/socks#92]
How to resolve this error?

**Comment by ChandlerAx** [comment]
Why close this instead of helping, ur not an "software engineer" who hired u 💀 retard.

**Comment by talmobi** [comment]
@ChandlerAx it's not a bug or an issue with the project -- you're just using it wrong most likely -- try and read the README and examples while using google to resolve it yourself and/or provide a detailed description of what you're doing and how it's going wrong along with your environment details -- we're not here to babysit you

**Comment by ChandlerAx** [comment]
> @ChandlerAx it's not a bug or an issue with the project -- you're just using it wrong most likely -- try and read the README and examples while using google to resolve it yourself and/or provide a detailed description of what you're doing and how it's going wrong along with your environment details -- we're not here to babysit you

At least provide some documentation/answer or information instead of closing this.

**Comment by JoshGlazebrook** [comment]
> > @ChandlerAx it's not a bug or an issue with the project -- you're just using it wrong most likely -- try and read the README and examples while using google to resolve it yourself and/or provide a detailed description of what you're doing and how it's going wrong along with your environment details -- we're not here to babysit you
> 
> At least provide some documentation/answer or information instead of closing this.

Try reading the README file and looking in the examples folder. Or maybe even read the source code, since you know this is an open source project and you can very easily attach a debugging and see what you are doing wrong from your end. Or perhaps actually provide a code snippet of what you are doing or any kind of actual question that is possible to answer.
