### ISSUE TITLE
Socks package depends on vulnerable package `ip`

### ISSUE THREAD

**Issue by dawidurbanski** [JoshGlazebrook/socks#93]
This package relies on a vulnerable [`ip`](https://github.com/indutny/node-ip) package.

[GHSA-78xj-cgh5-2h22](https://github.com/advisories/GHSA-78xj-cgh5-2h22)

The report says the affected versions are below `1.1.8` without any patched versions (latest is `2.0.0`, which this package relies on).

I took a moment to reproduce the vulnerability in `2.0.0` and this version is also affected (but not seen in npm audit, due to version constraint in the advisory database).

Maybe consider removing [`ip`](https://github.com/indutny/node-ip) as dependency.

This package seems to be dead, especially looking at the discousure timeline in the report:

> Disclosure Timeline
> 14 December 2022 - First Contact  [(via huntr):](https://huntr.com/bounties/bfc3b23f-ddc0-4ee7-afab-223b07115ed3/)
> 17 January 2023 - Reminder (No Response)
> 28 February 2023 - Reminder (No Response)
> 8 February 2024 - Public Disclosure

#### Is this package affected

The only two vulnerable functions from the `ip` package are [`isPublic`](https://github.com/indutny/node-ip/blob/main/lib/ip.js#L322C4-L324C2) and [`isPrivate`](https://github.com/indutny/node-ip/blob/main/lib/ip.js#L308C4-L320).

I didn't look through the code but you probably should ignore this if this package is not using these functions.

In such case this probably should be revisited only in case of the advisory database update stating the `2.0.0` package is also affected (making this package a culprit in the `npm audit`). Until then it's probably safe to ignore.

Related:
- https://github.com/TooTallNate/proxy-agents/issues/280
- https://github.com/TooTallNate/proxy-agents/pull/281

**Comment by JoshGlazebrook** [comment]
I'll work on removing it later today.

**Comment by JoshGlazebrook** [comment]
2.7.3 is published - https://www.npmjs.com/package/socks/v/2.7.3

#94
